parameters:
    env(TRANSPORT_DSN): 'php://default'
    env(ALLOW_ANONYMOUS): true
    transport_dsn: '%env(TRANSPORT_DSN)%'
    allow_anonymous: '%env(bool:ALLOW_ANONYMOUS)%'

services:
    _instanceof:
        Freddie\Hub\HubControllerInterface:
            tags: ['mercure.controller']
        Freddie\Hub\Transport\TransportFactoryInterface:
            tags: ['mercure.transport_factory']

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            iterable $controllers: !tagged_iterator mercure.controller


    Freddie\:
        resource: '%kernel.project_dir%/src/'
        exclude:
            - '%kernel.project_dir%/src/Hub/Transport/Redis/RedisPublisher.php'
            - '%kernel.project_dir%/src/Hub/Transport/Redis/RedisListener.php'
            - '%kernel.project_dir%/src/Hub/Transport/Redis/RedisTransport.php'
            - '%kernel.project_dir%/src/Kernel.php'
            - '%kernel.project_dir%/src/functions.php'

    Freddie\Hub\Controller\SubscribeController:
        arguments:
            $options:
                allow_anonymous: '%allow_anonymous%'

    Freddie\Security\JWT\Extractor\PSR7TokenExtractorInterface: '@Freddie\Security\JWT\Extractor\ChainTokenExtractor'
    Freddie\Hub\Transport\TransportFactory:
        arguments:
            $factories: !tagged_iterator mercure.transport_factory

    Freddie\Hub\Transport\TransportInterface:
        factory: ['@Freddie\Hub\Transport\TransportFactory', 'create']
        arguments: ['%transport_dsn%']

    FrameworkX\App:
        arguments:
            - '@Freddie\Hub\Middleware\HttpExceptionConverterMiddleware'
            - '@Freddie\Hub\Middleware\TokenExtractorMiddleware'

    Evenement\EventEmitter: ~
    Evenement\EventEmitterInterface: '@Evenement\EventEmitter'
    Clue\React\Redis\Factory: ~
